def generate_plain_text_report(project_name, inputs, results):
    """
    สร้างรายงาน Plain Text
    """
    report = f"""
==========================================================
STRUCTURAL CALCULATION REPORT: SOLAR RAIL DESIGN
Standard: AS/NZS 1170.2:2021
Project: {project_name}
==========================================================

[1] DESIGN PARAMETERS
---------------------
Testing Data (ASTM E290-14 Based):
  - Breaking Load: {inputs['breaking_load']:.2f} kN
  - Test Span:     {inputs['test_span']:.2f} m
  -> Calculated Mn: {results['Mn']:.2f} kNm

Solar Panel Data:
  - Size (W x D):  {inputs['panel_width']:.3f} m x {inputs['panel_depth']:.3f} m
  - Orientation:   Rails parallel to {inputs['rail_orient']}
  - Tributary Width: {results['trib_width']:.3f} m

Wind Load Parameters (AS/NZS 1170.2 - Section 5):
  - Design Wind Speed (V_des): {inputs['v_des']:.2f} m/s
  - Roof Angle:    {inputs['roof_angle']:.1f} degrees
  - Cpe (Interp.): {results['cpe']:.2f}
  - Coeffs (Ka,Kc,Kl,Kp): {inputs['coeffs']}
  - Design Pressure (p): {results['pressure_kpa']:.2f} kPa
  - Line Load on Rail (w): {results['w_load']:.2f} kN/m

[2] STRUCTURAL ANALYSIS (FEM)
-----------------------------
Method: Finite Element Method (Matrix Stiffness)
Configuration: Continuous Beam with {inputs['num_spans']} spans

Optimization Result:
  - Iterative check for M_design < Mn
  - Max Allowable Span: {results['opt_span']:.2f} m
  - M_design at Max Span: {results['m_design']:.2f} kNm
  - Mn Capacity: {results['Mn']:.2f} kNm
  - Utilization Ratio: {(results['m_design']/results['Mn'])*100:.1f} %

[3] CONCLUSION
--------------
The aluminum rail profile can support the solar installation 
with a maximum support spacing of {results['opt_span']:.2f} meters 
under the specified wind conditions.

==========================================================
Generated by AI Engineer (Gemini)
    """
    return report